export const JobCategoryOptions = [
    {"id": "admin_buiro", "name": "Administration/Biuro", "subcategory": [
        {"id": "secretary_reception", "name": "Secretary/reception"},
        {"id": "admin_buiro_work", "name": "Administration and biuro work"}
    ]},
    {"id": "research_development", "name": "Research and Development"},
    {"id": "banking", "name": "Banking"},
    {"id": "bhp_env", "name": "BHP and environemtal engineering"},
    {"id": "rep_cons", "name": "Repairing/Construction", "subcategory": [
        {"id": "architect", "name": "Architect"},
        {"id": "carpenter", "name": "Carpenter"},
        {"id": "roofer", "name": "Roofer"},
        {"id": "glazer", "name": "Glazer"},
        {"id": "hydraulics", "name": "Hydraulic worker"},
    ]},
    {"id": "delivery", "name": "Delivery"},
    {"id": "e_commerce", "name": "E-commerce"},
    {"id": "edu", "name": "Education"},
    {"id": "energetics", "name": "Energetics"},
    {"id": "fin_acc", "name": "Finances and accounting"},
    {"id": "franchise_entep", "name": "Franchise/Own firm"},
    {"id": "gastronomy", "name": "Gastronomy"},
    {"id": "hr", "name": "HR"},
    {"id": "hotel", "name": "Hotel industry"},
    {"id": "it", "name": "IT/Telecommunication", "subcategory": [
        {"id": "programmer", "name": "Programmer"},
        {"id": "tester", "name": "Tester"},
        {"id": "analytics", "name": "Analytics"},
        {"id": "tech_support", "name": "Technical support"},
        {"id": "admin_syst", "name": "System admin"},
        {"id": "admin_db", "name": "Database admin"},
        {"id": "admin_network", "name": "Network admin"},
        {"id": "project_manager", "name": "Project manager"},
    ]},
    {"id": "engineering", "name": "Engineering"},
    {"id": "driver", "name": "Driver"},
    {"id": "logistics", "name": "Logistics/Shipping"},
    {"id": "marketing", "name": "Marketing and PR"},
    {"id": "mech_vanish", "name": "Mechanics and vanishing"},
    {"id": "assembly_service", "name": "Assembly and service"},
    {"id": "real_estate", "name": "Real estate"},
    {"id": "call_center", "name": "Call Center"},
    {"id": "security", "name": "Security"},
    {"id": "caring", "name": "Caring"},
    {"id": "party_maker", "name": "Party maker"},
    {"id": "foreign_work", "name": "Foreign work"},
    {"id": "warehouse", "name": "Warehouse"},
    {"id": "store_emp", "name": "Store employee"},
    {"id": "law", "name": "Law"},
    {"id": "production", "name": "Production"},
    {"id": "gardening", "name": "Gardening"},
    {"id": "uniformed_services", "name": "Uniformed services"},
    {"id": "cleaning", "name": "Cleaning services"},
    {"id": "insurances", "name": "Insurances"},
    {"id": "display_goods", "name": "Display and arrangement of goods"},
    {"id": "health", "name": "Health"},
    {"id": "other", "name": "Other"},
];